/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as ProjectsRouteImport } from './app/projects'
import { Route as JobRouteImport } from './app/job'
import { Route as GraduationRouteImport } from './app/graduation'
import { Route as IndexRouteImport } from './app/index'
import { Route as ProjectsSlugRouteImport } from './app/projects.$slug'
import { Route as JobSlugRouteImport } from './app/job.$slug'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const JobRoute = JobRouteImport.update({
  id: '/job',
  path: '/job',
  getParentRoute: () => rootRouteImport,
} as any)
const GraduationRoute = GraduationRouteImport.update({
  id: '/graduation',
  path: '/graduation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjectsRoute,
} as any)
const JobSlugRoute = JobSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => JobRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/graduation': typeof GraduationRoute
  '/job': typeof JobRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/job/$slug': typeof JobSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/graduation': typeof GraduationRoute
  '/job': typeof JobRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/job/$slug': typeof JobSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/graduation': typeof GraduationRoute
  '/job': typeof JobRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/job/$slug': typeof JobSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/graduation'
    | '/job'
    | '/projects'
    | '/job/$slug'
    | '/projects/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/graduation'
    | '/job'
    | '/projects'
    | '/job/$slug'
    | '/projects/$slug'
  id:
    | '__root__'
    | '/'
    | '/graduation'
    | '/job'
    | '/projects'
    | '/job/$slug'
    | '/projects/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GraduationRoute: typeof GraduationRoute
  JobRoute: typeof JobRouteWithChildren
  ProjectsRoute: typeof ProjectsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job': {
      id: '/job'
      path: '/job'
      fullPath: '/job'
      preLoaderRoute: typeof JobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graduation': {
      id: '/graduation'
      path: '/graduation'
      fullPath: '/graduation'
      preLoaderRoute: typeof GraduationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/job/$slug': {
      id: '/job/$slug'
      path: '/$slug'
      fullPath: '/job/$slug'
      preLoaderRoute: typeof JobSlugRouteImport
      parentRoute: typeof JobRoute
    }
  }
}

interface JobRouteChildren {
  JobSlugRoute: typeof JobSlugRoute
}

const JobRouteChildren: JobRouteChildren = {
  JobSlugRoute: JobSlugRoute,
}

const JobRouteWithChildren = JobRoute._addFileChildren(JobRouteChildren)

interface ProjectsRouteChildren {
  ProjectsSlugRoute: typeof ProjectsSlugRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsSlugRoute: ProjectsSlugRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GraduationRoute: GraduationRoute,
  JobRoute: JobRouteWithChildren,
  ProjectsRoute: ProjectsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
